# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='founded_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
